#!/usr/bin/env bash
# $0 is the name of the file, and $1..$n are the others arguments
echo "The $0 script got the argument $1"
echo "Argument 2 is $2"
#PART 2
#$@ is the array of arguments
for i in $@
do
  echo $i
done
# $# is the number of arguments
echo "There were $# arguments"
