#!/usr/bin/env bash
# All these command have to be written at the command line
# in order to work
echo /tmp{one,two,three}/file.txt
#/tmp/one/file.txt  /tmp/two/file.txt /tmp/three/file.txt
echo c{a,o,u}t
#cat cot cut
echo /tmp/{1..3}/file.txt
#/tmp/1/file.txt  /tmp/2/file.txt /tmp/2/file.txt
echo {00..100}
#000 001 002 003 ... 100
echo {1..10}
#1 2 3 4 5 6 7 8 9 10
echo {10..1}
#10 9 8 7 6 5 4 3 2 1
echo {01..10}
#01 02 03 04 05 06 07 08 09 10
echo {a..z}
#a b c d e f g h i j k l m n o p q r s t u v w x y z
echo {Z..A}
#Z Y X W V U T S R Q P O N M L K J I H G F E D C B A
echo {1..30..3}
# 1 4 7 10 13 16 19 22 25 28
echo {a..z..2}
#a c e g i k m o q s u w y
echo {01..12}{a..d}
#01a 01b 01c 01d 02a 02b 02c ... 11c 11d 12a 12b 12c 12d
echo {cat,dog,fox}
# cat dog fox
echo {cat,dog,fox}_{1..5}
#cat_1 cat_2 cat_3 ... fox_3 fox_4 fox_5
