#!/usr/bin/env bash
#My case
case $((1+$RANDOM %6)) in
  1) echo "It was a one";;
  2) echo "It was a two";;
  3) echo "It was a three";;
  4) echo "It was a four";;
  5) echo "It was a five";;
  6) echo "It was a six";;
  *) echo -e "ERROR\a"
esac
#Course case
echo -e "\t\tWelcome to the"
echo -e "\t\t\033[5mMyStIcAl sPhErE\033[0m"
echo

waitingnumber=$((0+$RANDOM % 3))
mysterynumber=$((1+$RANDOM % 10))
declare -a fortunes=(
  "You are likely to achive the outcome you seek."
  "Today is not a good day to do that."
  "While it might seem unlikely,your chances are good."
  "If you belive you will be successful, that's half the battle."
  "If you cared enough to ask, you care enough to make it happen."
  "I think you already know the answer to that."
  "Stop wondering and start doing!"
  "Yes, sure, whatever, I'm busy."
  "Next Thursday might be a better day to do that."
  "Sure, but what will the neighbors think?"
)

case $waitingnumber in
  0) sleep 1; echo "One moment please..."; sleep 1;;
  1) sleep 1; echo "Your fortune will be along shortly..."; sleep 2;;
  2) sleep 1; echo "Preparing your fate..."; sleep 1;;
  3) sleep 1; echo "The veil of mystery is dark today..."; sleep 3;;
esac

echo
echo ${fortunes[mysterynumber]}
echo
