#!/usr/bin/env bash
echo $((4+4))
#8
echo $((8-5))
#3
echo $((2*3))
#6
echo $((8/4))
#2
echo $(((3+6)-5 * (5*2)))
#-41
#From here in order to work, you have to put them in the command line
a=3
((a+=3))
echo $a
#6
((a++))
echo $a
#7
((a++))
echo $a
#8
((a--))
echo $a
#7
(($a++))
#ERROR
((a++))
echo $a
#8
a=$a+2
echo $a
#8+2
declare -i b=3
b=$b+3
echo $b
#6
echo $((1/3))
#0
declare -i c=1
declare -i d=3
e=$(echo "scale=3; $c/$d" | bc)
#scale is the number of decimals
echo $e
#.333
echo $RANDOM
# XXXXX
echo $((1+$RANDOM %10))
# Random number between 1-10
echo $((1+$RANDOM %20))
# Random number between 1-20
