#!/usr/bin/env bash
echo "The results are: $((2+2)) and $((3/1))"
#The results are: 4 and 3
printf "The results are: %d and %d\n" $((2 + 2)) $(( 3 / 1))
#The results are: 4 and 3
#PART 2
echo "----10----| --5--"
echo "Right-aligned text and digits"
printf "%10s: %5d\n" "A label" 123 "B Label" 456
echo "Left-aligned text, right-aligned digits"
printf "%-10s: %5d\n" "A label" 123 "B Label" 456
echo "Left-aligned text and digits"
printf "%-10s: %-5d\n" "A label" 123 "B Label" 456
echo "Left-aligned text, right-aligned and padded digits"
printf "%-10s: %05d\n" "A label" 123 "B Label" 456
echo "----10----| --5--"
#PART 3
printf "%(%Y-%m-%d %H:%M:%S)T\n" 1279994448
date +%s
printf "%(%Y-%m-%d %H:%M:%S)T\n" $(date +%s)
printf "%(%Y-%m-%d %H:%M:%S)T\n"
printf "%(%Y-%m-%d %H:%M:%S)T is %s\n" -1 "the time"
