#!/usr/bin/env bash
#styles
bold="\033[1m"
normal="\033[0m"
greentext="\033[32m"
freespace=$(df -h |awk 'NR==2 {print $4}')
freemem=$(free -h |awk 'NR==2 {print $4}')
printf -v logdate "%(%Y-%m-%d)T"
echo -e $bold"Quick system report for "$normal$greentext "$HOSTNAME"$normal
printf "\tKernel Release:\t%s\n" $(uname -r)
printf "\tBash Version:\t%s\n" $BASH_VERSION
printf "\tFree Storage:\t%s\n" $freespace
printf "\tFree Memory:\t%s\n" $freemem
printf "\tFree Memory:\t%s\n" $(ls|wc -l)
printf "\tGenerated on:\t%s\n" $logdate
